# Script to deploy on the render cloud platforms

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: bounceapp/render-action@v0.61
      with:
        render-token: ${{secrets.RENDER_API_KEY}}
        github-token: ${{secrets.ACC_API_KEY}} # This is the github token
        service-id: "srv-cg90ltgtqv259v98u1kg" # This id is unique for each app
        retries: 20
        wait: 16000
        sleep: 30000
